# Generated by Django 6.0.1 on 2026-06-04 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memo", "0007_alter_memo_keywords"),
    ]

    operations = [
        migrations.AddField(
            model_name="memo",
            name="is_pinned",
            field=models.BooleanField(default=False, verbose_name="상단 고정"),
        ),
        migrations.AddField(
            model_name="memo",
            name="is_secret",
            field=models.BooleanField(default=False, verbose_name="내용 잠금"),
        ),
        migrations.AddField(
            model_name="memo",
            name="user_tags",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="사용자 태그"
            ),
        ),
        migrations.AlterField(
            model_name="memo",
            name="keywords",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="자동 키워드"
            ),
        ),
    ]
